### ISSUE TITLE
[Feature Request] 使用 ollama 进行本地推理

### ISSUE THREAD

**Issue by yjl9903** [SakuraLLM/Sakura-13B-Galgame#49]
https://ollama.com/

参考 https://github.com/SakuraLLM/Sakura-13B-Galgame/wiki/llama.cpp%E4%B8%80%E9%94%AE%E5%8C%85%E9%83%A8%E7%BD%B2%E6%95%99%E7%A8%8B 下载了 .gguf 的模型文件，和 https://github.com/ollama/ollama/blob/main/docs/modelfile.md

尝试写了以下 ollama 的 ModelFile 文件

```modelfile
FROM ./sakura-13b-lnovel-v0.9b-Q2_K.gguf

SYSTEM """你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上下文正确使用人称代词，不擅自添加原文中没有的代词。"""

TEMPLATE """{{ if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{ if .Prompt }}<|im_start|>user
将下面的日文文本翻译成中文：{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant"""

PARAMETER num_ctx 2048
PARAMETER temperature 0.1
PARAMETER top_p 0.3
PARAMETER repeat_penalty 1
PARAMETER num_predict 512
```

不确定是否需要设置这些参数，模型提到的参数（ https://github.com/SakuraLLM/Sakura-13B-Galgame?tab=readme-ov-file#%E6%8E%A8%E7%90%86 ），好像在 ollama 的文档里（ https://github.com/ollama/ollama/blob/main/docs/modelfile.md#parameter ）没有找到对应的

---

其次，试了一下似乎可以直接把 ollama 格式的模型发到它的平台上，https://ollama.com/onekuma/sakura-13b-lnovel-v0.9b-q2_k

```bash
# 从 ModelFile 创建模型
$ ollama create onekuma/sakura-13b-lnovel-v0.9b-q2_k -f Modelfile

# 把 ollama 的公钥复制到它的网站里
$ cat ~/.ollama/id_ed25519.pub

# 上传模型
$ ollama push onekuma/sakura-13b-lnovel-v0.9b-q2_k
```

然后用户可以一个命令，直接在本地使用

```bash
ollama run onekuma/sakura-13b-lnovel-v0.9b-q2_k
```

<img width="1317" alt="image" src="https://github.com/SakuraLLM/Sakura-13B-Galgame/assets/30072175/3e6b63f6-0109-4b99-9f3d-1e386fa81628">

---

看起来还挺方便、开箱即用的，最近也支持了 Windows，希望能上传一下，然后在 README 里提供一些教程。如果需要的话，我可以发 PR 帮助修改。

**Comment by NEKOparapa** [comment]
强烈支持哦，安装一大依赖啥，头都大了

**Comment by kice** [comment]
顺便可以白嫖一个webui，并且支持docker部署。

这里的docker compose，数据文件保存至 "/mnt/ollama/ollama" 和 "/mnt/ollama/ollama-webui" 两个目录。

访问`http://<服务器IP>:3000`，第一个注册的用户是管理员，不需要验证邮箱。

```
version: '3.8'

services:
  ollama:
    volumes:
      - /mnt/ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - /mnt/ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - '/ollama/api=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```
